### ISSUE TITLE
Install-EasyNovelAssistant.batを実行しても自動的に立ち上がらない

### ISSUE THREAD

**Issue by uikota** [Zuntan03/EasyNovelAssistant#10]
READMEの手順に従って[Install-EasyNovelAssistant.bat](https://github.com/Zuntan03/EasyNovelAssistant/raw/main/EasyNovelAssistant/setup/Install-EasyNovelAssistant.bat)を叩きましたが、
```
Traceback (most recent call last):
  File "D:\AI_NovelAssistant\EasyNovelAssistant\src\easy_novel_assistant.py", line 5, in <module>
    from form import Form
  File "D:\AI_NovelAssistant\EasyNovelAssistant\src\form.py", line 5, in <module>
    from input_area import InputArea
  File "D:\AI_NovelAssistant\EasyNovelAssistant\src\input_area.py", line 7, in <module>
    from watchdog.events import FileSystemEventHandler
ModuleNotFoundError: No module named 'watchdog'
Press any key to continue . . .
```
と仮想環境にモジュールがインストールされておらずエラーが発生するようです。

`Setup-EasyNovelAssistant.bat`を叩きモジュールをインストールすることで起動確認できたので問題ありませんが、
READMEを更新されるか`Install-EasyNovelAssistant.bat`でセットアップを完了させる必要があると思います。

**Comment by Zuntan03** [comment]
原因はわかっておりませんが、https://github.com/Zuntan03/EasyNovelAssistant/issues/8 と同じ案件だと思われます。
