### ISSUE TITLE
Install-Install-EasyNovelAssistant.batを実行するとモジュール 'watchdog' が見つからないエラーが発生する

### ISSUE THREAD

**Issue by haoblackj** [Zuntan03/EasyNovelAssistant#8]
`Install-Install-EasyNovelAssistant.bat` を実行したところ、次のエラーが表示され、EasyNovelAssistantが起動しませんでした。

```
Traceback (most recent call last):
  File "C:\TEMP\EasyNovelAssistant\EasyNovelAssistant\src\easy_novel_assistant.py", line 5, in <module>
    from form import Form
  File "C:\TEMP\EasyNovelAssistant\EasyNovelAssistant\src\form.py", line 5, in <module>
    from input_area import InputArea
  File "C:\TEMP\EasyNovelAssistant\EasyNovelAssistant\src\input_area.py", line 7, in <module>
    from watchdog.events import FileSystemEventHandler
ModuleNotFoundError: No module named 'watchdog'
```

必要な追加情報などありましたら、ご指示いただけますと幸いです。

**Comment by Zuntan03** [comment]
venv/Lib/site-packages にある watchdog-4.0.0.dist-info をその場にコピーして、
コピーしたフォルダ名を watchdog にリネームすると動作した過去事例がありました。

watchdog のインストールに失敗する原因は不明です。

**Comment by haoblackj** [comment]
早速ありがとうございます。
`Update-EasyNovelAssistant.bat` を実行したところ、エラー発生せず無事にEasyNovelAssistantが起動しました……。

同じエラーが出てきたら、リネームも試してみます。
